### PR TITLE
add memory-leak api

### PR DESCRIPTION
**Pull request by JiaxuanYang**

### CODE REVIEW

**Comment by steveww** [comment]
Thanks for the PR, I'll review this later this week.

**Comment by JiaxuanYang** [comment]
Hi @steveww , is there anything I need to change in my code?

**Comment by JiaxuanYang** [comment]
@steveww Did I missed anything?

**Comment by steveww** [comment]
I'm sure it's good, I've just not had time to review and merge yet. March is proving to be very busy and deadline heavy.

**Pull request merged**
