### PR TITLE
Add new images + added an option to add a Route for Openshift

### PR DESCRIPTION
**Pull request by dkaushik95**
- removed licensed images
- replaced with new images
- change the product image to png for consistency.
- changed the names of robots and their SKU.
- If users want a route to the web service, added a Route with the service

### CODE REVIEW

**Comment by steveww** [comment]
Thanks for the PR. I'll review and merge soon.

**Comment by steveww** [comment]
The image sizes are wrong. Only the SKU have been updated in the catalogue database.

I'm resizing the images and updating the descriptions. This will take a while.

**Comment by dkaushik95** [comment]
Instead of resizing the image, can I use css to resize it? I’ll do it on my side

**Comment by dkaushik95** [comment]
@steveww Can you check running locally? I have changed the image tag to resize the image to 300x300, so we won't need resizing.

**Comment by steveww** [comment]
Merged in with IBM PR

**Pull request closed without merging**
