### PR TITLE
Add script for patching services

### PR DESCRIPTION
**Pull request by dusansusic**
This is needed to get traces.

### CODE REVIEW

**Comment by dlbock** [comment]
This is a tangent. @steveww Can we make the robot-shop installation use the same yaml files as the K8s one at the very least? Or use `helm template` to generate a yaml that can be used for installation on OpenShift? It took us a long while to spot this missing `INSTANA_AGENT_HOST` env var. And the more different the installation methods are, the more things will diverge.

**Comment by dlbock** [comment]
If you want, I can figure out a way to do that `helm template` and open a PR for review

**Comment by steveww** [comment]
The K8s install YAML files have gone. Now the only way to install Robot Shop on K8s and it's various flavours is via Helm. The docs have been updated to match. HTH.

**Comment by dlbock** [comment]
@steveww Where are the docs updated for robot-shop installation on OpenShift? I don't see it in https://github.com/instana/robot-shop/tree/master/OpenShift, it still references the `deploy.sh` and `setup.sh` and still uses the docker-compose file.

**Comment by steveww** [comment]
@dlbock OpenShift now uses the Helm chart.

**Comment by dlbock** [comment]
@steveww Ok. The documentation still references the `deploy.sh` and `setup.sh` as I mentioned above. So will be good to update that.

**Comment by steveww** [comment]
@dlbock The documentation https://github.com/instana/robot-shop/tree/master/OpenShift has been updated. Which docs are you referring to?

**Comment by dlbock** [comment]
@steveww ah ok. it wasn't updated when I added the comment 4 days ago and apparently didn't refresh and read the page properly again an hour ago. 👍

**Pull request closed without merging**
